### ISSUE TITLE
Tabular numbers not well aligned

### ISSUE THREAD

**Issue by meduzen** [AleksandrHovhannisyan/fluid-type-scale-calculator#14]
On the following video, we see the total width taken by the number varies when the values change:

https://user-images.githubusercontent.com/9340937/150575548-45cfbe7d-dca7-4833-92c4-d64d4af315fe.mp4

This can be improved using CSS:

```css
.my-class-for-numbers {
  font-feature-settings: "tnum"; /* optional */
  font-variant-numeric: tabular-nums;
}
```

`font-variant-numeric` alone should be enough.

Knowledge reference:
- [The Smallest Difference](https://www.robinrendle.com/notes/the-smallest-difference/) by Robin Rendle
- [`font-feature-settings`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-feature-settings) on MDN
- [`font-variant-numeric`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-numeric) on MDN
